dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: rpnkEWZqvHEd0Iy0jtXU4CyI1Qe1kVF9yaR1ykgYokQIaUCidUxKdD0Gv7fpZrWl2ClT48UOksd9BUyhBVk1kfYbR0vCTjH8AE/j+cEflmzJhwAzpswHW0xp6g17lzx8J+nc8K28gsvmb7zLd+O1HR40zjBbjssLJ7pNzHfoVt6Gua7ZZsGFJZfxuqPAjVY/jP1ppO00WrDznEVL93ekak0uYxxuWUnoNKMV+2DSK8he7IOVQfrnZv2FHwIHAX9ozGpltMvCRHKkjQo7vwgkaRpcbZDgXp0sezhRvibAy+uqcixrIujXaRfD00O0kRnKF4mhZ8TL/xjeiyDAhmnUPyq/SJvHM2s0cttKWTMWcwnfRXMHtLqwomgVKDhobkymxCTgwRvFKixjAxPCxiUnlr9GX35nEl6ti2JUsic7dpM9081mddHzZsrst1Cps5l4N+jitROnEc1K4/NHMvM4WPgQAnY2WjgRaX6YzGrMRWH/RSfwSw8FhIVJFO+GihbOzBBhJlNG5z4X8M95dqpmfYmggAfoCy8GNMOH7P8k/Fsj4EWcIR5vcTsIGShMT56KDr4nMszal7dcHBzMx+UbJVGK1gzq/h486J6fvzYnYtZmHSbBxLCZkcNMwL6ILzjYz9w1y+BVfdIi+o3QvRTklF/3NONGdHsRFMzBDha2uKQ=
before_install:
- "rm -f $HOME/.npm/_logs/*-debug.log"
- openssl aes-256-cbc -K $encrypted_e466dd0f1e03_key -iv $encrypted_e466dd0f1e03_iv
  -in scripts/.npmrc.enc -out $HOME/.npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
